spring:
  servlet:
    multipart:
      max-file-size: 100000KB
      max-request-size: 100000KB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: username
    password: password
    hikari:
      idle-timeout: 10000
 # datasource:
  #  url: jdbc:mariadb://lab02-db00006770.mdb0002865.db.skysql.net:5050/devices?createDatabaseIfNotExist=true&useSsl=true&serverSslCert=src\main\resources\skysql_chain.pem
   # driver-class-name: org.mariadb.jdbc.Driver
    #username: DB00006770
    #password: VIeL2|PmtY0kR4IStPOMEAf
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ddl-auto: create
        format_sql: false
    #    dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    




#5050 --user DB00006770 -p --ssl-ca ~/Downloads/skysql_chain.pem
 #       
# spring.datasource.url=jdbc:mariadb://localhost:3306/springbootdb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
#datasource:
#    type: com.zaxxer.hikari.HikariDataSource

#    url: jdbc:h2:mem:TEST
#    driver-class-name: org.h2.Driver
#   username: username
#   password: password
#    hikari:
#     idle-timeout: 10000
#
#
#
